#!/bin/bash

## Linux Obsidian Build Script
## By Mohamed Tarek <https://github.com/xjlsigmaboy>

# colors
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
magneta=$(tput setaf 5)
cyan=$(tput setaf 6)
white=$(tput setaf 7)
reset=$(tput sgr0)

## Varibales
cores=$(nproc)
version=6
patchlevel=13
sublevel=5
subname='obsidian'
vtb=$version.$patchlevel.$sublevel
source=https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-$version.$patchlevel.$sublevel.tar.xz

#source=https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-$version.$patchlevel.tar.xz

mkdir src
cd src
wget $source

tar xvf linux-$version.$patchlevel.$sublevel.tar.xz
#tar xvf linux-$version.$patchlevel.tar.xz

# Configuration
cp config/.config linux-$version.$patchlevel.$sublevel/

# Cores
printf "[$green*$reset] Cores used to build?(max =$red $cores$reset):"
read usedcores


# building
echo "[$green*$reset] Kernel Version: $red$vtb$reset"
echo "[$green*$reset] Starting building!"


make -j$usedcores


